/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteFeedbackRouteImport } from './routes/_site/feedback'
import { Route as SiteLinksRouteImport } from './routes/_site/links'
import { Route as SiteReservationRouteImport } from './routes/_site/reservation'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminFeedbackRouteImport } from './routes/admin/feedback'
import { Route as AdminInformasiRouteImport } from './routes/admin/informasi'
import { Route as AdminReservationRouteImport } from './routes/admin/reservation'
import { Route as AdminUploadRouteImport } from './routes/admin/upload'
import { Route as SitePostsSlugRouteImport } from './routes/_site/posts.$slug'
import { Route as SiteTagsIndexRouteImport } from './routes/_site/tags.index'
import { Route as SiteTagsSlugRouteImport } from './routes/_site/tags.$slug'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFeedbackRoute = SiteFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => SiteRoute,
} as any).lazy(() =>
  import('./routes/_site/feedback.lazy').then((d) => d.Route),
)
const SiteLinksRoute = SiteLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => SiteRoute,
} as any)
const SiteReservationRoute = SiteReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => SiteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() => import('./routes/admin/index.lazy').then((d) => d.Route))
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() =>
  import('./routes/admin/feedback.lazy').then((d) => d.Route),
)
const AdminInformasiRoute = AdminInformasiRouteImport.update({
  id: '/informasi',
  path: '/informasi',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() =>
  import('./routes/admin/informasi.lazy').then((d) => d.Route),
)
const AdminReservationRoute = AdminReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() =>
  import('./routes/admin/reservation.lazy').then((d) => d.Route),
)
const AdminUploadRoute = AdminUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() => import('./routes/admin/upload.lazy').then((d) => d.Route))
const SitePostsSlugRoute = SitePostsSlugRouteImport.update({
  id: '/posts/$slug',
  path: '/posts/$slug',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTagsIndexRoute = SiteTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTagsSlugRoute = SiteTagsSlugRouteImport.update({
  id: '/tags/$slug',
  path: '/tags/$slug',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/': typeof SiteIndexRoute
  '/feedback': typeof SiteFeedbackRoute
  '/links': typeof SiteLinksRoute
  '/reservation': typeof SiteReservationRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/informasi': typeof AdminInformasiRoute
  '/admin/reservation': typeof AdminReservationRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/': typeof AdminIndexRoute
  '/posts/$slug': typeof SitePostsSlugRoute
  '/tags/$slug': typeof SiteTagsSlugRoute
  '/tags/': typeof SiteTagsIndexRoute
}
export interface FileRoutesByTo {
  '/feedback': typeof SiteFeedbackRoute
  '/links': typeof SiteLinksRoute
  '/reservation': typeof SiteReservationRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/informasi': typeof AdminInformasiRoute
  '/admin/reservation': typeof AdminReservationRoute
  '/admin/upload': typeof AdminUploadRoute
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminIndexRoute
  '/posts/$slug': typeof SitePostsSlugRoute
  '/tags/$slug': typeof SiteTagsSlugRoute
  '/tags': typeof SiteTagsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/_site/feedback': typeof SiteFeedbackRoute
  '/_site/links': typeof SiteLinksRoute
  '/_site/reservation': typeof SiteReservationRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/informasi': typeof AdminInformasiRoute
  '/admin/reservation': typeof AdminReservationRoute
  '/admin/upload': typeof AdminUploadRoute
  '/_site/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_site/posts/$slug': typeof SitePostsSlugRoute
  '/_site/tags/$slug': typeof SiteTagsSlugRoute
  '/_site/tags/': typeof SiteTagsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/'
    | '/feedback'
    | '/links'
    | '/reservation'
    | '/admin/feedback'
    | '/admin/informasi'
    | '/admin/reservation'
    | '/admin/upload'
    | '/admin/'
    | '/posts/$slug'
    | '/tags/$slug'
    | '/tags/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/feedback'
    | '/links'
    | '/reservation'
    | '/admin/feedback'
    | '/admin/informasi'
    | '/admin/reservation'
    | '/admin/upload'
    | '/'
    | '/admin'
    | '/posts/$slug'
    | '/tags/$slug'
    | '/tags'
  id:
    | '__root__'
    | '/admin'
    | '/_site'
    | '/_site/feedback'
    | '/_site/links'
    | '/_site/reservation'
    | '/admin/feedback'
    | '/admin/informasi'
    | '/admin/reservation'
    | '/admin/upload'
    | '/_site/'
    | '/admin/'
    | '/_site/posts/$slug'
    | '/_site/tags/$slug'
    | '/_site/tags/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/feedback': {
      id: '/_site/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof SiteFeedbackRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/links': {
      id: '/_site/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof SiteLinksRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/reservation': {
      id: '/_site/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof SiteReservationRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/informasi': {
      id: '/admin/informasi'
      path: '/informasi'
      fullPath: '/admin/informasi'
      preLoaderRoute: typeof AdminInformasiRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reservation': {
      id: '/admin/reservation'
      path: '/reservation'
      fullPath: '/admin/reservation'
      preLoaderRoute: typeof AdminReservationRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/upload': {
      id: '/admin/upload'
      path: '/upload'
      fullPath: '/admin/upload'
      preLoaderRoute: typeof AdminUploadRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_site/posts/$slug': {
      id: '/_site/posts/$slug'
      path: '/posts/$slug'
      fullPath: '/posts/$slug'
      preLoaderRoute: typeof SitePostsSlugRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/tags/': {
      id: '/_site/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof SiteTagsIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/tags/$slug': {
      id: '/_site/tags/$slug'
      path: '/tags/$slug'
      fullPath: '/tags/$slug'
      preLoaderRoute: typeof SiteTagsSlugRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminInformasiRoute: typeof AdminInformasiRoute
  AdminReservationRoute: typeof AdminReservationRoute
  AdminUploadRoute: typeof AdminUploadRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminInformasiRoute: AdminInformasiRoute,
  AdminReservationRoute: AdminReservationRoute,
  AdminUploadRoute: AdminUploadRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface SiteRouteChildren {
  SiteFeedbackRoute: typeof SiteFeedbackRoute
  SiteLinksRoute: typeof SiteLinksRoute
  SiteReservationRoute: typeof SiteReservationRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SitePostsSlugRoute: typeof SitePostsSlugRoute
  SiteTagsSlugRoute: typeof SiteTagsSlugRoute
  SiteTagsIndexRoute: typeof SiteTagsIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteFeedbackRoute: SiteFeedbackRoute,
  SiteLinksRoute: SiteLinksRoute,
  SiteReservationRoute: SiteReservationRoute,
  SiteIndexRoute: SiteIndexRoute,
  SitePostsSlugRoute: SitePostsSlugRoute,
  SiteTagsSlugRoute: SiteTagsSlugRoute,
  SiteTagsIndexRoute: SiteTagsIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
