/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as SiteFeedbackRouteImport } from './routes/_site/feedback'
import { Route as SiteLinksRouteImport } from './routes/_site/links'
import { Route as SiteReservationRouteImport } from './routes/_site/reservation'
import { Route as SiteTagsRouteImport } from './routes/_site/tags'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminFeedbackRouteImport } from './routes/admin/feedback'
import { Route as AdminInformasiRouteImport } from './routes/admin/informasi'
import { Route as AdminReservationRouteImport } from './routes/admin/reservation'
import { Route as AdminUploadRouteImport } from './routes/admin/upload'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteFeedbackRoute = SiteFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => SiteRoute,
} as any).lazy(() =>
  import('./routes/_site/feedback.lazy').then((d) => d.Route),
)
const SiteLinksRoute = SiteLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => SiteRoute,
} as any)
const SiteReservationRoute = SiteReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTagsRoute = SiteTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => SiteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() => import('./routes/admin/index.lazy').then((d) => d.Route))
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() =>
  import('./routes/admin/feedback.lazy').then((d) => d.Route),
)
const AdminInformasiRoute = AdminInformasiRouteImport.update({
  id: '/informasi',
  path: '/informasi',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() =>
  import('./routes/admin/informasi.lazy').then((d) => d.Route),
)
const AdminReservationRoute = AdminReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() =>
  import('./routes/admin/reservation.lazy').then((d) => d.Route),
)
const AdminUploadRoute = AdminUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AdminRouteRoute,
} as any).lazy(() => import('./routes/admin/upload.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/admin': typeof AdminRouteRouteWithChildren
  '/': typeof SiteIndexRoute
  '/feedback': typeof SiteFeedbackRoute
  '/links': typeof SiteLinksRoute
  '/reservation': typeof SiteReservationRoute
  '/tags': typeof SiteTagsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/informasi': typeof AdminInformasiRoute
  '/admin/reservation': typeof AdminReservationRoute
  '/admin/upload': typeof AdminUploadRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/feedback': typeof SiteFeedbackRoute
  '/links': typeof SiteLinksRoute
  '/reservation': typeof SiteReservationRoute
  '/tags': typeof SiteTagsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/informasi': typeof AdminInformasiRoute
  '/admin/reservation': typeof AdminReservationRoute
  '/admin/upload': typeof AdminUploadRoute
  '/': typeof SiteIndexRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin': typeof AdminRouteRouteWithChildren
  '/_site': typeof SiteRouteWithChildren
  '/_site/feedback': typeof SiteFeedbackRoute
  '/_site/links': typeof SiteLinksRoute
  '/_site/reservation': typeof SiteReservationRoute
  '/_site/tags': typeof SiteTagsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/informasi': typeof AdminInformasiRoute
  '/admin/reservation': typeof AdminReservationRoute
  '/admin/upload': typeof AdminUploadRoute
  '/_site/': typeof SiteIndexRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/admin'
    | '/'
    | '/feedback'
    | '/links'
    | '/reservation'
    | '/tags'
    | '/admin/feedback'
    | '/admin/informasi'
    | '/admin/reservation'
    | '/admin/upload'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/feedback'
    | '/links'
    | '/reservation'
    | '/tags'
    | '/admin/feedback'
    | '/admin/informasi'
    | '/admin/reservation'
    | '/admin/upload'
    | '/'
    | '/admin'
  id:
    | '__root__'
    | '/admin'
    | '/_site'
    | '/_site/feedback'
    | '/_site/links'
    | '/_site/reservation'
    | '/_site/tags'
    | '/admin/feedback'
    | '/admin/informasi'
    | '/admin/reservation'
    | '/admin/upload'
    | '/_site/'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/feedback': {
      id: '/_site/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof SiteFeedbackRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/links': {
      id: '/_site/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof SiteLinksRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/reservation': {
      id: '/_site/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof SiteReservationRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/tags': {
      id: '/_site/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof SiteTagsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/informasi': {
      id: '/admin/informasi'
      path: '/informasi'
      fullPath: '/admin/informasi'
      preLoaderRoute: typeof AdminInformasiRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reservation': {
      id: '/admin/reservation'
      path: '/reservation'
      fullPath: '/admin/reservation'
      preLoaderRoute: typeof AdminReservationRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/upload': {
      id: '/admin/upload'
      path: '/upload'
      fullPath: '/admin/upload'
      preLoaderRoute: typeof AdminUploadRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminInformasiRoute: typeof AdminInformasiRoute
  AdminReservationRoute: typeof AdminReservationRoute
  AdminUploadRoute: typeof AdminUploadRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminInformasiRoute: AdminInformasiRoute,
  AdminReservationRoute: AdminReservationRoute,
  AdminUploadRoute: AdminUploadRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface SiteRouteChildren {
  SiteFeedbackRoute: typeof SiteFeedbackRoute
  SiteLinksRoute: typeof SiteLinksRoute
  SiteReservationRoute: typeof SiteReservationRoute
  SiteTagsRoute: typeof SiteTagsRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteFeedbackRoute: SiteFeedbackRoute,
  SiteLinksRoute: SiteLinksRoute,
  SiteReservationRoute: SiteReservationRoute,
  SiteTagsRoute: SiteTagsRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
